### ISSUE TITLE
X_PLEX_TOKEN

### ISSUE THREAD

**Issue by laouache** [wernight/docker-plex-media-server#28]
Hi,

I tried to use your docker with x_plex_token or PLEX_LOGIN to configure automatically the docker to run under à specific user at startup.

But when i go to parameters/server i have an error message : parameters are not available.

I use the configuration of docker-compose below :

docker-compose with PLEX_LOGIN OR X_PLEX_TOKEN

```
plex-media-server:
  image: "wernight/plex-media-server:latest"
  container_name: plex-media-server
  ports:
      - "32400:32400"
  environment:
    PLEX_LOGIN: ${PLEX_LOGIN}
    PLEX_PASSWORD: ${PLEX_PASSWORD}
  volumes:
      - ${MEDIA}:/media
      - ${PLEX_CONFIG}:/config
  restart: always
  hostname: ${PLEX_HOSTNAME}
```

Could you help me ?
Do you want more logs ?
