### ISSUE TITLE
autoupdate (plexpass) image keeps restarting with "runuser: System error"

### ISSUE THREAD

**Issue by kientran** [wernight/docker-plex-media-server#35]
Host OS: [Linux]
Tag/Version: [autoupdate]

Steps:
1. create docker-compose as follows:
```
plex:
    #build: ./docker-plex-media-server
    image: wernight/plex-media-server:autoupdate
    volumes:
      - /mnt/tank/configs/plexmediaserver:/config
      - /mnt/tank/tv:/tv
      - /mnt/tank/Movies:/movies
    environment:
      - X_PLEX_TOKEN=abcdefgHIJKLMNO
    network_mode: host
    restart: always
```

2. docker-compose up -d plex

Expected:
Functioning plex

Actual:
Plex container continuously restarts
```
docker logs -tf mediaserver_plex_1
....
2017-01-03T07:56:45.666178930Z runuser: System error
2017-01-03T07:58:28.165394391Z runuser: System error
....
```
```
docker exec -it mediaserver_plex_1 bash
tail -f docker.log
ERRO[16165688] Error setting up exec command in container mediaserver_plex_1: Container mediaserver_plex_1 is restarting, wait until the container is running 
ERRO[16165688] Handler for POST /v1.22/containers/mediaserver_plex_1/exec returned error: Container mediaserver_plex_1 is restarting, wait until the container is running
```

Any thoughts?  Had to drop back down to "latest" and was up and running again.
