### ISSUE TITLE
Can't reach my server from external

### ISSUE THREAD

**Issue by PixiBixi** [wernight/docker-plex-media-server#43]
Host OS: [Linux]
Tag/Version: [autoupdate]

Hello!

I try to reach my server from an external source, but i cant. I've no idea why, i have the same issue with the timhaak container.

There's my docker-compose

```yaml
  plex:
    restart: always
    image: wernight/plex-media-server:autoupdate
    container_name: plex
    volumes:
      - /data/incoming:/media
      - /home/dedi/.apps/plex/config:/config
    environment:
      - PLEX_LOGIN=x
      - PLEX_PASSWORD=x
    ports:
      - "32400:32400"
    environment:
      - VIRTUAL_HOST=x
      - VIRTUAL_PORT=32400
      - LETSENCRYPT_EMAIL=contact@x
      - LETSENCRYPT_HOST=x
```

Of course, i can reach the web interface of Plex from an external source..
